### ISSUE TITLE
Some deploy mechanism is overriding our rest results on github pages

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1106]
**Describe the bug**

Some deploy mechanism is overriding our rest results on github pages.
On branch gh-pages some workflow was deleting / overriding test results (852d30600e66ec4ab004b0dbcf2f9a88d6578fcf)

**To Reproduce**
unknown yet

**Expected behavior**

missing:
https://thin-edge.github.io/thin-edge.io/results/report-matrix.html

available:
https://abelikt.github.io/thin-edge.io/results/report-matrix.html

**Comment by rina23q** [comment]
I know the reason because I had the similar issue of pushing version bump-up related commits by two bots. Both workflow push the commits to same branch. The solution is to specify to the branch where to push in at least one workflow.

We should use this option `publish_branch`. https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-another-github-pages-branch-publish_branch

```
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_branch: your-branch  # default: gh-pages
```
