### ISSUE TITLE
Support variable interpolation inside configuration file contents

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1725]
**Is your feature improvement request related to a problem? Please describe.**

Support variables interpolation inside configuration files so make it easier to create generic configuration which is easier to change and maintain.

For example, the `c8y-log-plugin.toml` file (used by `c8y-log-plugin`) includes default settings about where to get the `software-management` configuration files which are created by `tedge-agent`. The `path` for the `software-management` setting is actually dependent on the tedge configuration inside the `/etc/tedge/tedge.toml` file.

If the user changes the default location of the `logs.path` setting, e.g. `tedge config set logs.path /opt/log`, then the `c8y-log-plugin.toml` no longer refers to the new path where tedge is writing the log files to. This forces the user to have to think about which other configuration files are not essentially broken, and they have to track them down and fix them to align with the new global `/opt/log` directory.

**Example configuration for `c8y-log-plugin.toml`**

Below is an example showing the default `c8y-log-plugin.toml` file as created by `c8y-log-plugin --init` during installation.

*file: `/etc/tedge/c8y/c8y-log-plugin.toml`*

```toml
files = [
    {
       type = "software-management",
       path = "/var/log/tedge/agent/software-*",  # <<---- this path is dependent on the `logs.path` setting in the tedge.toml
    },  
]
```

**Describe the solution you'd like**

Add support for interpolating/referencing specific tedge configuration from inside configuration files, such as `c8y-log-plugin.toml`, which is then expanded by the appropriate plugin at runtime. This could also be extended to also provide more sources, such as environment variables as well.

For example, a simple template syntax `{{ <config>.<path> }}` (or something similar) could be used by users which will reference to the path current used by tedge.

The same configuration from the previous section, could be rewritten using references to `{{ tedge.logs.path }}` instead of the static string `/var/log`.

```toml
files = [
    {
       type = "software-management",
       path = "{{ tedge.logs.path }}/tedge/agent/software-*",  # <<---- use reference to the tedge 'logs.path' setting
    },
]
```

The concept could also be extended to also support reference environment variables, e.g. `{{ env.MY_GLOBAL_VAR }}` which would use the environment variable `MY_GLOBAL_VAR` value.

This syntax makes the configuration files more portable across different devices, and it is much easier for the user to maintain and change.

Other aspects which need refinement
* How to specify default values if the reference variable does not exist? (e.g. ignore the entry, or use a default value?)
* Work out exact syntax (maybe something that 

**Describe alternatives you've considered**

**Additional context**
