### ISSUE TITLE
Create role based default configs for tedge operation plugins

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2447]
**Is your feature improvement request related to a problem? Please describe.**

The `tedge-log-plugin` and `tedge-config-plugin` currently creates their configuration files with zero file entries (all example entries commented), as they can run both on main device as well as child devices and those examples only make sense on the main device. Leaving them empty on child devices is acceptable as we can't assume any paths on those devices. But, at least on the main device, some sensible default entries should be present, so that someone using these plugins get to try out those features immediately, without having to update those files.

**Describe the solution you'd like**

* The default plugin config file contents should be generated based on the role (main device or not)
* The config paths of tedge config files (`tedge.toml`, `system.toml` etc) in `tedge-configuration-plugin.toml` should not assume the default config dir: `/etc/tedge` but rather derive it from the `--config-dir` option that's used to invoke that plugin
* The `tedge-log-plugin.toml` on the main device should at least have the tedge-agent/software-management entries in it.

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
The following would be the suggested default settings both the configuration and log management features:

**file: /etc/tedge/plugins/tedge-log-plugin.toml**

```toml
[[files]]
type = "software-management"
path = "/var/log/tedge/agent/software-*"
```


**file: /etc/tedge/plugins/tedge-configuration-plugin.toml**

```toml
[[files]]
path = "/etc/tedge/tedge.toml"
type = "tedge.toml"

[[files]]
path = "/etc/tedge/plugins/tedge-log-plugin.toml"
type = "tedge-log-plugin"
user = "tedge"
group = "tedge"
mode = 0o0444
```
