### ISSUE TITLE
Tedge config settings to selectively enable/disable supported operations of tedge-agent

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2459]
**Is your feature request related to a problem? Please describe.**

Since the `tedge-configuration-plugin` and the `tedge-log-plugin` have been merged into the `tedge-agent`, there should be a mechanism to disable their corresponding operations (`config_snapshot`, `config_update`, `log_upload`) should the user want to opt-out of their usage. Previously the user could have just disabled the tedge-log-plugin or tedge-configuration-plugin service, but since it is now one single service (tedge-agent), another mechanism is required to disable the functionality.

**Describe the solution you'd like**

Provide a tedge config setting: `agent.enable.<op_name>` to enable/disable each supported operation individually as follows:

The scope is explicitly limited to the functionality previously delivered by the tedge-log-plugin and tedge-configuration-plugin (e.g. `log_upload`, `config_update` and `config_snapshot`).

```toml
[agent]
enable.log_upload = true
enable.config_update = true
enable.config_snapshot = true
```

**Describe alternatives you've considered**

The `enable` settings could also be placed under those operation specific config roots as follows:

```toml
[configuration]
enable = true

[log_upload]
enable = true

# ...other op sections
```

The only downside with this approach is that the `agent` is not mentioned anywhere in the key and a user may misinterpret it as the whole feature is disabled, whereas we're only disabling the inbuilt ops handling by the agent.

But the proposed solution also comes with the downside that the enable/disable settings are isolated from the rest of the feature specific config settings mentioned above. Ideally, those feature specific settings should also be moved under the `agent` root setting, alongside their `enable` keys, without breaking backward compatibility as follows:

```toml
[agent.software_management]
enable = true

[agent.software_management.plugin]
default = "apt"
max_packages = 1000

[agent.firmware_management]
enable = true

[agent.firmwaremanagement.child.update]
timeout = 30

[agent.config_management]
enable = true

[agent.log_management]
enable = true
```

**Additional context**
