### ISSUE TITLE
support triggering a workflow from a custom cloud operation handler

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2845]
**Is your feature improvement request related to a problem? Please describe.**

Allow customer operation handlers to trigger thin-edge.io commands (e.g. `te/+/+/+/+/cmd/+` topics) allowing customer operations to work for both the main device and child devices (if the child-device also have the tedge-agent installed).

thin-edge.io commands have the advantage that they support the workflow model which allows users to define custom steps related to the handling of the commands. The workflows make it easy to integrate complex actions in the workflow steps to perform planned device and service restarts, and the operation will continue after the action is finished (something not currently supported by the custom cloud operation handlers).

**Describe the solution you'd like**

Support triggering a workflow from a cloud operation/message.

For example, one possible solution would be to extend the existing custom cloud operation handler to support calling a workflow:

**file: /etc/tedge/operations/c8y/set_wifi**

A new property called `operation` could be defined instead of `command` which will publish a MQTT message to the related `te/{target_identifier}/cmd/{id}` topic.

```toml
[exec]
operation = "set_wifi"
topic = "c8y/s/dc/custom_devmgmt"
on_message = "dm101"
```

**Notes**
* It might also make sense to also support transforming the incoming payload from the cloud to a generic format so that the workflow does not have to do any cloud specific logic (e.g. detect which cloud the information is coming from and normalize it accordingly).
* There will have to be away for the cloud operation updates to be delegated to the workflow status changes rather than from the custom operation handler, as currently the mapper will automatically sent the operation to executing/successful/failed

A `set_wifi` workflow file could be then provided by the user to define what should be done.

**file: /etc/tedge/operations/set_wifi.toml**

```toml
operation = "set_wifi"

[init]
action = "proceed"
on_success = "executing"

[executing]
action = "builtin"
on_success = "apply"

[apply]
script = "/usr/bin/set_wifi.sh --name ${.payload.name} --ssid ${.payload.ssid} --type ${.payload.type}"
on_success = "successful"

[successful]
action = "cleanup"

[failed]
action = "cleanup"
```

**Describe alternatives you've considered**

**Additional context**
