### ISSUE TITLE
feat(workflow): support combining fixed strings with variable expansions

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2847]
**Is your feature improvement request related to a problem? Please describe.**

The variable expansion supported by the tedge-agent workflow syntax is too restrictive and does not support combining fixed strings with a variable

For example the following `script` will not be expanded as the `tedge-mapper-`

```toml
script = "sudo systemctl restart tedge-mapper-${.payload.mapperType}"
```

Because of that, if the user wants to build a script argument by combining a fixed string with a variable reference, they would then need to create a wrapper script which will do the string interpolation.

For example the above would have to be write a wrapper script, e.g. `/usr/bin/my_wrapper.sh`:

```sh
#!/bin/sh
sudo systemctl restart "tedge-mapper-$1"
```

And then call the wrapper script from the workflow state:

```toml
script = "/usr/bin/my_wrapper.sh ${.payload.mapperType}"
```

Writing a wrapper script adds too much overhead and is harder to maintain as it is easy for the wrapper script to get out of sync with the workflow definition.

**Describe the solution you'd like**

Support expanding variable references (e.g. `${<dotnotation>}`) even when a static prefix/suffix is provided (or even multiple variable references in the same argument?)

```toml
operation = "restart_mapper"

[init]
action = "proceed"
on_success = "executing"

[executing]
script = "sudo systemctl restart tedge-mapper-${.payload.mapperType}"
on_success = "successful"

[successful]
action = "cleanup"

[failed]
action = "cleanup"
```

**Describe alternatives you've considered**

**Additional context**
