### ISSUE TITLE
avoid explicit path to c8y-remote-access-plugin in operation definition

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#3111]
**Is your feature improvement request related to a problem? Please describe.**

The `c8y_RemoteAccessConnect` operation definition created via `c8y-remote-access-plugin --init` assumes the location of the binary is under `/usr/bin/c8y-remote-access-plugin`. When the c8y-remote-access-plugin is installed in a custom location, this results in a non-functional operation handler.

Below shows the generated operation file:

**file: /etc/tedge/operations/c8y/c8y_RemoteAccessConnect**

```toml
[exec]
command = "/usr/bin/c8y-remote-access-plugin"
topic = "c8y/s/ds"
on_message = "530"
```

**Describe the solution you'd like**

The `exec.command` field should not use a explicit path to the binary, and instead just use `c8y-remote-access-plugin` to allow the user to control the location via standard `PATH` environment variable.

For example, the following shows the desired result: 

**file: /etc/tedge/operations/c8y/c8y_RemoteAccessConnect**

```toml
[exec]
command = "c8y-remote-access-plugin"
topic = "c8y/s/ds"
on_message = "530"
```

**Describe alternatives you've considered**

Technically the full path to the c8y-remote-access-plugin binary could be used at the time it is run, however this would not allow for the binaries to be relocated without having to re-run the `c8y-remote-access-plugin --init` command.

**Additional context**
