### ISSUE TITLE
support calling complex commands in custom operation definitions

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#3186]
**Is your feature improvement request related to a problem? Please describe.**

When defining a custom operation handler, the `exec.command` field does not accept a complex commands definitions as it passes everything after the first whitespace as a single argument to the given binary.

For example, below is a custom c8y_Command operation handler which just publishes a dummy message using `tedge mqtt pub`:

**file: /etc/tedge/operations/c8y/c8y_Command**

```toml
[exec]
topic = "c8y/devicecontrol/notifications"
on_fragment = "c8y_Command"
command = "tedge mqtt pub test ${.payload.c8y_Command}"
skip_status_update = false
```

Sending a c8y_Command operation then results in the following error

**log: /var/log/tedge/agent/c8y_Command-2024-10-14T21:35:35.510365905Z.log**

```sh
# cat c8y_Command-2024-10-14T21:35:35.510365905Z.log
----- $ /usr/bin/tedge "mqtt pub test {\"text\":\"echo test\"}"
Exit status: 2 (ERROR)

stderr <<EOF
error: unrecognized subcommand 'mqtt pub test {"text":"echo test"}'

  tip: a similar subcommand exists: 'mqtt'

Usage: tedge [OPTIONS] <COMMAND>

For more information, try '--help'.
EOF

stdout (EMPTY)
```

**Describe the solution you'd like**

Use `shell_words::split` when parsing the `exec.command` property of a custom operation definition. This will align with the workflow `script` property.

**Describe alternatives you've considered**

**Additional context**
