### ISSUE TITLE
protect against user misconfiguration of the tedge-configuration-plugin.toml

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#3491]
**Is your feature improvement request related to a problem? Please describe.**

Protect against user misconfiguration if they try to override the `tedge-configuration-plugin`.

For example, if the someone adds the following contents the following file:

**file: /etc/tedge/plugins/tedge-configuration-plugin.toml**

```toml
[[files]]
# Use an invalid path!
path = '/etc/wrongpath/tedge-configuration-plugin.toml'
type = 'tedge-configuration-plugin'
user = 'tedge'
group = 'tedge'
mode = 0o444

[[files]]
path = '/etc/tedge/plugins/example.toml'
type = 'example'
user = 'tedge'
group = 'tedge'
mode = 0o644
```

Afterwards, in the Cumulocity Device Management UI, only the "tedge-configuration-plugin" type is found and not the "example" type. The root cause seems to be because the user had accidentally overridden the `tedge-configuration-plugin` with a path that does not exist, or at least it is not then read afterwards.

For users, it is no so obvious what the issue is.

**Describe the solution you'd like**

The tedge-configuration-plugin.toml should protect itself against misconfiguration of the `tedge-configuration-plugin` type which then causes the management of the other configuration files.

* Option 1 (preferred): Log a warning when the incorrect path to the tedge-configuration-plugin.toml path is used, but the incorrect path should be replaced with the correct path
* Option 2: Fail the operation if the user is provides a new tedge-configuration-plugin.toml operation and add a failure reason explaining that the path is incorrect.

**Describe alternatives you've considered**

**Additional context**
