### ISSUE TITLE
Allow custom operation handlers to be defined for azure and aws mappers

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#3653]
**Is your feature request related to a problem? Please describe.**

Currently thin-edge.io the AWS and Azure mappers do not support the custom operation definitions, which results in the user having to write their own client which does the mapping of incoming messages from the cloud and translates them to tedge commands.

For example, the following definition is ignore by the tedge-mapper-aws.

```toml
# cat /etc/tedge/operations/aws/software_update.template
[exec]
topic = "aws/shadow/cmd/software_update"
on_fragment = "software_update"

[exec.workflow]
operation = "software_update"
input = "${.payload.software_update}"
output = "${.payload.result}"
```

**Describe the solution you'd like**

Allow users to write custom operation handlers under `/etc/tedge/operations/aws/` and `/etc/tedge/operations/az/` to make it easier to trigger tedge commands from other clouds.

**Describe alternatives you've considered**

**Additional context**
